### ISSUE TITLE
Sonic In The Mod?

### ISSUE THREAD

**Issue by Sonicthe06** [Retro64Mod/Retro64Mod.github.io#100]
this was a cool mod in the port and i would like to see a skin of it in the future if you ever make this my year would be better :) :edit i dont regret asking a mod from the port to be in the game lol also are you gonna make a bedrock version of the mod? its maybe its to hard for you
![Screenshot 2022-05-10 140244](https://user-images.githubusercontent.com/105401700/168933750-200b0988-9b0b-4b55-9fe9-2c0f077e5ca5.png)

**Comment by dylanpdx** [comment]
Do you have a link to this model?
