### ISSUE TITLE
problem with launching

### ISSUE THREAD

**Issue by Pro123play** [Retro64Mod/Retro64Mod.github.io#106]
the mod didnt see the ROM,but its in folder(screenshots is existing). need help with this. if i tried press the "m" button game crashes . i did like in your video, jar and dll versions is identical,
![image](https://user-images.githubusercontent.com/89829083/168463972-de8ea450-52a4-425c-b059-ae45cd5a7c08.png)

**Comment by Pro123play** [comment]
i donno how to fix this

**Comment by dylanpdx** [comment]
The rom must be in z64 format, not n64.

**Comment by Pro123play** [comment]
okie dokie, i try to download this
tnx for help

**Comment by Pro123play** [comment]
ITS WORKS! thanks a lot to you

**Comment by Pro123play** [comment]
and i got a litle question, its offtopic, but i need to ask: how do the long-jump in minecraft?

**Comment by Pro123play** [comment]
i saw the other youtubers doing it, but i donno how

**Comment by RealGranfill** [comment]
All you have to do is run then chrouch then immidietly jump
