### ISSUE TITLE
A minor bug with the mechanics 

### ISSUE THREAD

**Issue by RayCatYT** [Retro64Mod/Retro64Mod.github.io#107]
When falling off a block, there is a slight chance you bug and go superspeed while on the edge. 
Can be recreated using a wall and one half of a floor, as seen in the video.
(But not entirely recreated, since the wall is exatly in the direction where you would go superspeed

https://user-images.githubusercontent.com/68147363/168657183-db1a3788-7660-4285-9c94-307da8eec900.mp4

)

**Comment by dylanpdx** [comment]
I think this is a bug on the Sm64 side of things (i.e is present in the original game) but I can't quite verify that

**Comment by dylanpdx** [comment]
This is a SM64 issue which I'll probably not fix to keep the physics similar to the real game.
