### ISSUE TITLE
Can't open Retro64 menu

### ISSUE THREAD

**Issue by Chateauvisionn** [Retro64Mod/Retro64Mod.github.io#111]
When i press Z or M, nothing happens what can i do? (the mod is loaded and i have this [link removed] rom)

**Comment by dylanpdx** [comment]
Check your keybinds to make sure they're set to the Z and M keys. Not sure why they'd be different but something may be conflicting

**Comment by SupertM8ario** [comment]
Hi Im New Can You Show Me The Z.64
