### ISSUE TITLE
Confused about the "rom"

### ISSUE THREAD

**Issue by pogpuppy** [Retro64Mod/Retro64Mod.github.io#112]
So while looking at the instructions i never really understood what the "rom" file was or even how to get it. Then when I open minecraft and press m, it goes frozen for a split second then crashes. And it does warn me before i open minecraft that the rom file is missing. Please help.

**Comment by dylanpdx** [comment]
The ROM file is a file containing the data that would be in a real SM64 cartridge. Unfortunately due to legal reasons, unless you own a real cartridge, I can't say anything further about how you'd get one.

**Comment by pogpuppy** [comment]
Alright now i understand. Thank you!
