### ISSUE TITLE
Minecraft Crashing on Startup

### ISSUE THREAD

**Issue by Evanzap** [Retro64Mod/Retro64Mod.github.io#122]
When i open minecraft, it crashes.
I only have the baserom, genfiles and retro64 1.0.9
Exit Code: -1073740791

**Comment by dylanpdx** [comment]
More info needed
OS? Crash log? 

Also, genfiles is no longer required

**Comment by Evanzap** [comment]
Here's a log. Also i use windows 1
[latest.log](https://github.com/Retro64Mod/Retro64Mod.github.io/files/8838139/latest.log)
1

**Comment by dylanpdx** [comment]
I need the crash log, it should be in the crash-reports folder

**Comment by Evanzap** [comment]
![Screenshot_32](https://user-images.githubusercontent.com/49214424/172013089-90e4d9b4-329d-43a8-83fa-f53ae4ce3b02.png)
look im sorry but there's literally no crash-reports folder.

**Comment by dylanpdx** [comment]
I see you're using the Curseforge client, in that case it might be in a different place. Check Curse/Minecraft/Install instead of in Instances. If there's still no crash-reports folder you can also try and send me the launcher_log.txt which should be there if it's Curse

**Comment by Evanzap** [comment]
still no crash reports folder but heres the launcher log
[launcher_log.txt](https://github.com/Retro64Mod/Retro64Mod.github.io/files/8838189/launcher_log.txt)

**Comment by dylanpdx** [comment]
I suspect this might be an issue with Curse, but I'm not able to replicate it. Once Curse launches the MC launcher, try going into the Installations tab, editing the forge install, click on "More options" and reset the JVM Arguments

![image](https://user-images.githubusercontent.com/1337360/172014896-d8ec9a1b-7c32-4f35-bde9-3cefcd1ab745.png)

**Comment by Evanzap** [comment]
possibly, after doing that it crashed with the same exit code. let me try doing it on not curse.

**Comment by Evanzap** [comment]
nope, it may be an issue with my machine and there's still no crash logs.

**Comment by dylanpdx** [comment]
Apparently certain Nvidia drivers or Razer synapse can cause that error code, but since I assume the game works without the mod, it's probably not the issue

https://bugs.mojang.com/browse/MC-112780

I'm still not sure if this is a PC issue or something related to how I packaged the mod, but I don't see any log messages from the mod when starting up so I'm leaning more towards a PC issue
