### ISSUE TITLE
The Slabs and Stairs have Wrong collisions

### ISSUE THREAD

**Issue by RealGranfill** [Retro64Mod/Retro64Mod.github.io#123]
The Slabs and Stairs have Wrong Collisions

**Comment by dylanpdx** [comment]
Can you explain more about the issue? What collisions should they have? What are you experiencing instead?

**Comment by RealGranfill** [comment]
when i tried doing the blj glitch The slabs had collisions of a normal 1x-1y minecraft block, Also Stairs do that, Please fix the collision of the slabs to be 1x-1y, also fix the stair collisions btw the blj didn't work :(

**Comment by RealGranfill** [comment]
> Can you explain more about the issue? What collisions should they have? What are you experiencing instead?

when i tried doing the blj glitch The slabs had collisions of a normal 1x-1y minecraft block, Also Stairs do that, Please fix the collision of the slabs to be 1x-1y, also fix the stair collisions btw the blj didn't work :(

**Comment by dylanpdx** [comment]
This sounds like an issue with OptiFine. Shaders need to be fully disabled (not set to internal) in order for collisions to work properly.
