### ISSUE TITLE
Mario can catch on fire

### ISSUE THREAD

**Issue by lowercas** [Retro64Mod/Retro64Mod.github.io#13]
If mario walks into the corner of a lava tile, he will start burning just like regular Minecraft

![IMG_1212](https://user-images.githubusercontent.com/80478955/158722922-d4908e9a-1bc5-41f8-ba43-64cda8fb49de.jpg)

**Comment by NobodyYouKnow01** [comment]
Similar issue with lavafalls: Mario will treat falling lava as a wall instead of reacting to it.
https://imgur.com/a/F7uTKRl

**Comment by dylanpdx** [comment]
Fixed in https://github.com/Retro64Mod/Retro64Mod/commit/92336219cf7723cf62bf0dfe9f6b2c78f3699051
