### ISSUE TITLE
Minecraft crashes immediately when the title screen appears.

### ISSUE THREAD

**Issue by Joeswano** [Retro64Mod/Retro64Mod.github.io#130]
Right when the loading bar finishes and the title screens starts to fade in, the game crashes. Right before it crashes, it says "Saving World..." for a split second.

I put in both the mod (1.0.9) and the correct version of the rom into the mods folder, use Forge version 40.0.45 for Minecraft 1.18.2, and then it crashes. I'm using the vanilla launcher.

I'm using a MacBook Air with an M1 chip on Big Sur [11.6.]
[crash-2022-06-21_17.39.06-client.txt](https://github.com/Retro64Mod/Retro64Mod.github.io/files/8952954/crash-2022-06-21_17.39.06-client.txt)

**Comment by dylanpdx** [comment]
You may need to install SDL2 through brew. I'll update the installation instructions if it works for you
Command should be `brew install sdl2`
