### ISSUE TITLE
many issues with instillation

### ISSUE THREAD

**Issue by fnfmodder32** [Retro64Mod/Retro64Mod.github.io#131]
**Describe the bug**
1: there is no minecraft forge version between 1.18.1 and 1.19
2: i need javafml 37 and idk how to get that using the provided download as it has no installer
3: forge version is out of date even though i have the latest version
**Minecraft Version**
cant bc there are none

**Mod Version**
latest
**Minecraft launcher**
Vanilla

**Please attach Screenshots or Crash logs if relevant to the bug**

**Desktop (please complete the following information):**
 Windows
 10

**Additional context**

**Comment by dylanpdx** [comment]
https://files.minecraftforge.net/net/minecraftforge/forge/index_1.18.2.html
