### ISSUE TITLE
Error in french

### ISSUE THREAD

**Issue by Gabin293** [Retro64Mod/Retro64Mod.github.io#132]
- On file: "[Retro64Mod/src/main/resources/assets/retro64/lang/fr_fr.json](https://github.com/Retro64Mod/Retro64Mod/blob/6253dc9af4610677a4055428ddc0453e37dc6519/src/main/resources/assets/retro64/lang/fr_fr.json)"

**On line:** [8] `"charSelect.retro64.prev": "Avant",` (before)
**It should be:** `"charSelect.retro64.prev": "Précédent",` (previous) _Like, "previous page"..._

**Comment by dylanpdx** [comment]
Fixed in https://github.com/Retro64Mod/Retro64Mod/commit/1500024e69cffc3e9e8916182ba600b732602a2a
