### ISSUE TITLE
Effect Problem

### ISSUE THREAD

**Issue by Sonicthe06** [Retro64Mod/Retro64Mod.github.io#133]
When Adding The Speed Effect To Mario His Run Animation Stops Moving And Running Then  Jumping Causes Something In One Of The Videos Down There.

How To Do It
Go In Retro64 Mode Then Do This Command /effect give @s minecraft:speed 999999 100 and enter walk you should see this

https://user-images.githubusercontent.com/105401700/177452714-ff1824a6-b65e-4572-9014-b734082d6ac7.mp4

When You Jump While Walking You Should Also See This

https://user-images.githubusercontent.com/105401700/177452857-0f5e9596-78d5-4427-973f-44f2be57541b.mp4

What i used to do this glitch
Minecraft Forge Version
1.18.2

Mod Version
1.9

Minecraft Launcher
Normal Launcher

PC
 - OS: [Windows 11]
 - Version [Latest]

This Is A Speed Effect Problem

https://user-images.githubusercontent.com/105401700/177412033-d7937871-ff7b-415c-8989-7afe5b96facf.mp4

https://user-images.githubusercontent.com/105401700/177412038-484215ac-28a2-4d0a-9b6d-5122a0fe2555.mp4

**Comment by dylanpdx** [comment]
Only "natural" speeds are supported at the moment, i.e 999999 won't work as that's too fast for the sm64 engine. May fix this in the future but atm it's not planned
