### ISSUE TITLE
Rom hack bug

### ISSUE THREAD

**Issue by IconicPlushStarsReal** [Retro64Mod/Retro64Mod.github.io#136]
**Describe the bug**
When you put a modded rom in the mc mods folder the jar file should not allow any rom that is not vanilla

**To Reproduce**
1.  Add a modded rom with any vanilla rom like a patcher for roms

**Minecraft Version**
Enter the Minecraft version you are on
1.18.2
**Mod Version**
1.0.10

**Minecraft launcher**
Vanilla

**Please attach Screenshots or Crash logs if relevant to the bug**

**Desktop (please complete the following information):**
 - Windows
 - Version 10
**Additional context**

**Comment by dylanpdx** [comment]
Already implemented
