### ISSUE TITLE
tlauncher crashes when booting up mc with the mod

### ISSUE THREAD

**Issue by kirbydark714** [Retro64Mod/Retro64Mod.github.io#137]
**Describe the bug**
when booting up mc in tlaucher it crashes
**To Reproduce**
1. boot up mc in tlaucher with the mod in the folder
2. done
**Minecraft Version**
Enter the Minecraft version you are on
1.18.2
**Mod Version**
Enter the version of the mod you are using
1.0.9
**Minecraft launcher**
Enter the launcher you are using, i.e Vanilla, MultiMC, CurseForge, etc.
tlauncher
**Please attach Screenshots or Crash logs if relevant to the bug**
[crash-2022-07-22_23.02.07-client.txt](https://github.com/Retro64Mod/Retro64Mod.github.io/files/9170438/crash-2022-07-22_23.02.07-client.txt)
**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Version [e.g. 10]
windows 10
**Additional context**

**Comment by dylanpdx** [comment]
Will look into this, seems to be an issue when displaying the ROM selection GUI

**Comment by dylanpdx** [comment]
TLauncher is not supported
