### ISSUE TITLE
Rubidium Visual Incompatibility

### ISSUE THREAD

**Issue by bassistracer** [Retro64Mod/Retro64Mod.github.io#144]
**Describe the bug**
Rubidium causes Mario's textures to glitch out and be semi-transparent. Tried it with the Steve player model and he seemed to basically take the texture of whatever my camera was pointed towards at the time.

**To Reproduce**
1. Get Rubidium (and Rubidium Extras/Dynamic Lights/Oculus)
2. ???
3. profit

**Mod Version**
1.0.10

**Minecraft launcher**
PolyMC

**Additional context**
amazing job so far

**Comment by dylanpdx** [comment]
Any mod that modifies the rendering engine (Optifine, Sodium, Rubidium, etc.) is not supported at the moment
