### ISSUE TITLE
Game not loading

### ISSUE THREAD

**Issue by linkplayz0** [Retro64Mod/Retro64Mod.github.io#147]
**Describe the bug**
Whenever I try to load into the game with the mod installed, the game gets past the Mojang Studios screen, then the game closes.

**To Reproduce**
1. I… uh don’t know? I followed all the steps on the website.

**Minecraft Version**
1.18.2

**Mod Version**
1.0.9

**Minecraft launcher**
Curseforge, patched for macOS voice chat mods

**Please attach Screenshots or Crash logs if relevant to the bug**

**Desktop (please complete the following information):**
 - OS: macOSX
 - Version: 12.5

**Comment by dylanpdx** [comment]
Updated install instructions with a not for Mac users: https://retro64mod.github.io/
The new step requires installing brew and SDL2 to fix an issue with audio compatibility.
Let me know if it worked for you.

**Comment by linkplayz0** [comment]
Thanks, it works now!
