### ISSUE TITLE
No Sound On mac

### ISSUE THREAD

**Issue by Figgy2112** [Retro64Mod/Retro64Mod.github.io#151]
Hi, I'm Playing The Mod On Forge 1.18.12/40.1.20 On A 2014 Macbook Pro Running 11.6.4 (Big Sur) And Everything is Working Except The Sound, All The Minecraft Sound Are The But Mario Has No Sound, I Followed All The Steps And Don't Know What To Do, The Rom I Just Got From The Internet Archive And I Installed Homebrew And SDL2, Please Help

**Comment by dylanpdx** [comment]
I'll leave this open, but I believe the next update fixes this issue

**Comment by TheDsquadYT** [comment]
No sound on Mac yea

**Comment by TheDsquadYT** [comment]
Im having same issue

**Comment by dylanpdx** [comment]
Should be fixed in 1.0.12
https://github.com/Retro64Mod/Retro64Mod/releases/tag/1.18.2-1.0.12
