### ISSUE TITLE
Chest and Beds not existing

### ISSUE THREAD

**Issue by SpongeSteveTheOriginal** [Retro64Mod/Retro64Mod.github.io#152]
When i play as mario, he can walk true chests and beds, idk if any other non full blocks, but things like grinder do work with hitbox(mario can't go true it). And 2 more bugs, campfires and composters teleported me from one side to the other and back, and chain could be used as a race start, cuz it puts u in that mode after walking true it

Minecraft version: 1.18.2 | Forge version: 40.0.24 | Optifine? = Yes

Mod version:1.0.9

pictures:
![Snímek obrazovky (265)](https://user-images.githubusercontent.com/116765496/198149885-33d2bf35-4fcd-4428-948f-e585c0739c88.png)
![Snímek obrazovky (266)](https://user-images.githubusercontent.com/116765496/198149894-a25daf46-aa92-42a6-b5e4-742f5b8bd4dc.png)

Launcher: Curseforge

Desktop
 - OS: Windows 10

would be good if you would fix the bed bug but chain is what you could maybe even represent, and by that u can make a race from START to end (Start= chain)

**Comment by dylanpdx** [comment]
Should be fixed on https://github.com/Retro64Mod/Retro64Mod/releases/tag/1.18.2-1.0.12
