### ISSUE TITLE
Put the .JAR file in a downloads section

### ISSUE THREAD

**Issue by LP222222** [Retro64Mod/Retro64Mod.github.io#158]
Make it so that the .JAR file can be downloaded in 1.19 for forge so I don't have to risk my computer getting a virus(I don't trust .BAT files from online).

**Comment by SirenGlitch** [comment]
the mod doesn't support 1.19, if its a .bat file, its fake.

**Comment by dylanpdx** [comment]
Beta now available at https://github.com/Retro64Mod/Retro64Mod/releases/tag/1.19.2-1.0.12
