### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by Dummy3434** [Retro64Mod/Retro64Mod.github.io#161]
So, when i boot the game, it works all fine, execpt when i load a world i made in that version, it gets stuck on loading terrain. It just freezer and if i click on the screen it just telle me its not working poperly. Here's the file of the error  (Edit:it does not come up for some reason)
![Immagine 2022-11-29 190911](https://user-images.githubusercontent.com/119443651/204611758-78c9fe05-a86c-476f-81f9-5ab60da98c78.png)

**Comment by Dummy3434** [comment]
By the way, it says:we verified a problem and the game was arrested in an abnormal way. We are sorry for the inconvenience.
this abnormal arrest may be fixed allocating more memory in the configuration of this version of minecraft java edition.
Im using windows btw

**Comment by dylanpdx** [comment]
Do you have OptiFine installed? Might be related to #148

**Comment by Dummy3434** [comment]
oh i actually dont

**Comment by Dummy3434** [comment]
thanks bro

**Comment by Dummy3434** [comment]
OMG IT WORKS THANK YOU YOU ARE THE BEST
