### ISSUE TITLE
Trojan Detected

### ISSUE THREAD

**Issue by Dricogamesyt** [Retro64Mod/Retro64Mod.github.io#162]
Hey Well My Anti-Virus Detected a Trojan Inside Your Mario64 mod Multiple Times, as So i Think This is a Miss Intended Feature.
![image](https://user-images.githubusercontent.com/119623536/205133409-036014cc-85a2-4f25-92d6-8e4a3d155737.png)
As i Wish Please Remove The Trojan As Its A Virus Launcher Basically

**Comment by Dricogamesyt** [comment]
**i'd really recommend removing the trojan so people don't think its a virus**

**Comment by dylanpdx** [comment]
There is no trojan in it, it's just a false positive. I really can't "remove" anything because it doesn't exist.
