### ISSUE TITLE
Mario corruption

### ISSUE THREAD

**Issue by SirenGlitch** [Retro64Mod/Retro64Mod.github.io#166]
**Describe the bug**
Mario model corruption (am yet to test others)
**To Reproduce**
1. Load game
2. Switch to mario mode (M key)
3. F5
4. Make mario face camera

**Minecraft Version**
1.18.2

**Mod Version**
retro64-1.0.10.jar

**Minecraft launcher**
Prism Launcher

**Please attach Screenshots or Crash logs if relevant to the bug**
<img width="180" alt="Screenshot 2023-01-21 123413" src="https://user-images.githubusercontent.com/110285018/213867280-c730a5f3-b765-48d4-a266-592dd3ce3410.png">

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10

**Additional context**
Sometimes turns green and invisible

**Comment by dylanpdx** [comment]
Are you using any mods that alter the game's rendering engine? i.e OptiFine, Sodium/Lithium, etc.
Those currently aren't compatible with the mod

**Comment by SirenGlitch** [comment]
> Are you using any mods that alter the game's rendering engine? i.e OptiFine, Sodium/Lithium, etc.
> Those currently aren't compatible with the mod

I have Rubidium for the video screen change. I'm guessing since that is a sodium fork that it is the problem then?

**Comment by dylanpdx** [comment]
Most likely, yes. Anything that deals with changing how MC renders things seems to have issues with this mod
