### ISSUE TITLE
i need help to launche the game i do all correctly but minecraft give me an error:

### ISSUE THREAD

**Issue by lapizzacadente** [Retro64Mod/Retro64Mod.github.io#167]
**Describe the bug**

**To Reproduce**
1. 

**Minecraft Version**
Enter the Minecraft version you are on

**Mod Version**
Enter the version of the mod you are using

**Minecraft launcher**
Enter the launcher you are using, i.e Vanilla, MultiMC, CurseForge, etc.

**Please attach Screenshots or Crash logs if relevant to the bug**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Version [e.g. 10]

**Additional context**
![Immagine 2023-01-29 113430](https://user-images.githubusercontent.com/123828236/215320726-c23d9c28-bd41-4ac4-b0c8-f899782770b3.png)
![Immagine 2023-01-29 113510](https://user-images.githubusercontent.com/123828236/215320730-852c1c92-cb5a-4c9b-9a64-6b00b6fe55fe.png)

**Comment by djhatt0204** [comment]
The Rom you put in the folder is not the correct file type. You need a .z64 file, not a .n64

**Comment by dylanpdx** [comment]
You have the incorrect ROM type. It needs to be .z64
