### ISSUE TITLE
Sound not working on macOS

### ISSUE THREAD

**Issue by Sammy3968** [Retro64Mod/Retro64Mod.github.io#168]
There is no sound whatsoever coming from Mario, jumping, kicking, backflipping, ledge-grabbing basically everything has no sound. no sound effects or voice clips

_quick note that Minecraft sounds are unaffected and that it's just Mario_

I am on the mod version 1.0.10 and on Minecraft 1.18.2 w/ Vanilla Launcher

to reproduce the issue literally just download the game and run it

I am using a 2021 Macbook Pro with M1 Pro

**Comment by dylanpdx** [comment]
Please try the latest release, available here: https://github.com/Retro64Mod/Retro64Mod/actions/runs/3942046936

**Comment by Sammy3968** [comment]
it works now, nice
