### ISSUE TITLE
Fucking game crashes when i start it 

### ISSUE THREAD

**Issue by df7cye78ryweRUN4122** [Retro64Mod/Retro64Mod.github.io#169]
Soooooo the flipping game crashes when i start in on TLauncher and what does the fucking game runs on?Forge?Fabric?Or is it just vanilla Minecraft?HOW DO I FIX THIS DINGUS IT MAKES ME SO MAD 
![Captura de Tela (39)](https://user-images.githubusercontent.com/125316402/218583864-bc5d9248-9a23-4db8-8278-175ee44b863c.png)

**Comment by df7cye78ryweRUN4122** [comment]
> Soooooo the flipping game crashes when i start in on TLauncher and what does the fucking game runs on?Forge?Fabric?Or is it just vanilla Minecraft?HOW DO I FIX THIS DINGUS IT MAKES ME SO MAD ![Captura de Tela (39)](https://user-images.githubusercontent.com/125316402/218583864-bc5d9248-9a23-4db8-8278-175ee44b863c.png)

also my real name is Lucas its just GitHub that dosent FUCKING ALLOW ANY HUMAN NAME

**Comment by dylanpdx** [comment]
TLauncher is not supported with Retro64
