### ISSUE TITLE
I don't think blj (backwards long jump launch) works any more.... Plzz fix it

### ISSUE THREAD

**Issue by TheDsquadYT** [Retro64Mod/Retro64Mod.github.io#172]
**Describe the bug**

**To Reproduce**
1. 

**Minecraft Version**
Enter the Minecraft version you are on

**Mod Version**
Enter the version of the mod you are using

**Minecraft launcher**
Enter the launcher you are using, i.e Vanilla, MultiMC, CurseForge, etc.

**Please attach Screenshots or Crash logs if relevant to the bug**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Version [e.g. 10]

**Additional context**

**Comment by dylanpdx** [comment]
Please fill out the template correctly
