### ISSUE TITLE
Crash on Mac

### ISSUE THREAD

**Issue by TheDsquadYT** [Retro64Mod/Retro64Mod.github.io#175]
**Describe the bug**
Every time I upload the latest 10.12 version, it crashes but the 10.10 1 is fine! idk if its only for Mac or for all platforms

**Minecraft Version**
1.18.2

**Mod Version**
10.12

**Minecraft launcher**
normal Minecraft launcher
**Please attach Screenshots or Crash logs if relevant to the bug**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Version [e.g. 10]

**Additional context**

**Comment by Ezekielman** [comment]
Are you on an Intel Mac or an M1 Mac?

**Comment by dylanpdx** [comment]
Please fill out the template correctly, including OS and version of the mod you are using
![image](https://user-images.githubusercontent.com/1337360/226187613-51d14979-b62d-4f9a-ae30-ad8275227341.png)
