### ISSUE TITLE
Falling interactions with snow and ice are backwards

### ISSUE THREAD

**Issue by NobodyYouKnow01** [Retro64Mod/Retro64Mod.github.io#18]
Expected behavior: 
When Mario falls onto ice, he should take fall damage.
When Mario falls onto snow, he should do the stuck animation.

Actual behavior:
When Mario falls onto snow, he takes fall damage.
When Mario falls onto ice, he does the suck animation.

https://imgur.com/a/57BfhMB

**Comment by Mario9501** [comment]
The ice is correct as it does that in the vanilla game as well
