### ISSUE TITLE
No Flying Cap in 1.19.3-1.0.13?

### ISSUE THREAD

**Issue by altheawesomeguy** [Retro64Mod/Retro64Mod.github.io#180]
I couldn't help but notice that the Mario flying cap does not appear or function after equipping the elytra anymore. I know it's pre-release, just didn't see any mention of it yet.

**Comment by dylanpdx** [comment]
That has been replaces with dedicated wing, metal, and vanish items in the creative tab for Retro64

**Comment by altheawesomeguy** [comment]
Oh thank you!
