### ISSUE TITLE
Cannot run this mods on pojavlauncher (Minecraft java for mobile)

### ISSUE THREAD

**Issue by thenono48rayan1** [Retro64Mod/Retro64Mod.github.io#188]
**Describe the bug**
Error code -1 crash problem
**To Reproduce**
1. When i start Minecraft at the loading it crash and say error code -1

**Minecraft Version**
Enter the Minecraft version you are on
1.18.2
**Mod Version**
Enter the version of the mod you are using
1.0.13
**Minecraft launcher**
Enter the launcher you are using, i.e Vanilla, MultiMC, CurseForge, etc.
pojavlauncher
**Please attach Screenshots or Crash logs if relevant to the bug**
No need screenshot i already said it
**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Version [e.g. 10]
Android 11
**Additional context**
That the only things i said

**Comment by dylanpdx** [comment]
Only Windows, Linux, and Mac are supported at the moment. There's so much variation in android devices that I can't really support them all at the moment.

**Comment by thenono48rayan1** [comment]
Oh it's ok
