### ISSUE TITLE
needs a rom file

### ISSUE THREAD

**Issue by Jowbee5** [Retro64Mod/Retro64Mod.github.io#196]
**Describe the bug**
I open minecraft with the mod and it ask for a rom file

**To Reproduce**
1. downloud the file, open curseforge make a modpack in 1.18.2, then put retro64 in the mods foder. then you play the modpack and when you're in minecraft it will say your mising a rom file so it will acks for one.

**Minecraft Version**
1.18.2

**Mod Version**
1.18.2-1.0.13

**Minecraft launcher**
CurseForge

**Please attach Screenshots or Crash logs if relevant to the bug**

**Desktop (please complete the following information):**
 Windows 10

**Comment by dylanpdx** [comment]
You need to get the ROM file yourself, I cannot provide it.
