### ISSUE TITLE
Linux Audio

### ISSUE THREAD

**Issue by JavaJacket1** [Retro64Mod/Retro64Mod.github.io#201]
I noticed on release tag 1.19.2-1.0.12 You said "Fixed audio on Mac and Linux, among other bugfixes".

This implies that there is audio support for linux but I can't seem to find it anywhere.  I can only find  genfiles.exe v1

Does this linux support file exist?

If so where can I get it?

Anything helps! Thank You.

**Comment by dylanpdx** [comment]
genfiles.exe is no longer required.
Please read the updated installation instructions on https://retro64mod.github.io/
