### ISSUE TITLE
ROM not found

### ISSUE THREAD

**Issue by asdaeshndj** [Retro64Mod/Retro64Mod.github.io#22]
when i trying to run the mod the mod said that the rom not found even thought i got the sm64 rom

**Comment by NobodyYouKnow01** [comment]
Have you tried renaming the rom to baserom.us.z64 and included it in the mods directory?

**Comment by dylanpdx** [comment]
Name doesn't matter as long as it's the USA .z64 version

**Comment by asdaeshndj** [comment]
thank you it is working now
