### ISSUE TITLE
Sound cut off on low fps

### ISSUE THREAD

**Issue by PinguLinux** [Retro64Mod/Retro64Mod.github.io#24]
Also mario moves slower, maybe missing deltatime?

**Comment by dylanpdx** [comment]
The audio thread runs separately from  MC so i'm not sure why this is happening, will look into it, but i've heard allocating more RAM might help

**Comment by RetroStem** [comment]
> 

how much ram do you recommend allocating for the minimum and maximum

**Comment by dylanpdx** [comment]
> > how much ram do you recommend allocating for the minimum and maximum
2gb or more for minimum

Also, please let me know if this is still happening on the latest version (1.0.9)
