### ISSUE TITLE
the only thing is that when i click get versions it doent give me anything and it is skipping please fix

### ISSUE THREAD

**Issue by lol123468** [Retro64Mod/Retro64Mod.github.io#27]
the only thing is that when i click get versions it doent give me anything and it is skipping please fix

**Comment by lol123468** [comment]
file:///C:/Users/GamerX/Videos/VSDC%20Free%20Screen%20Recorder/vsdc-sr%202022-03-18%2014-09-33.mp4

**Comment by dylanpdx** [comment]
Uninstall and Reinstall MSYS2?

**Comment by baccobaccobacco** [comment]
Potentially same issue here. After clicking "Get Versions" the terminal runs for a bit, but gives an error (see screenshot). Clicking continue does nothing and nothing appears in the versions dropdown.
![image](https://user-images.githubusercontent.com/101949716/159136984-aa1d96f9-3d5e-4796-b059-439adb704759.png)

**Comment by dylanpdx** [comment]
If you're sure you have the most recent version of MSYS2, make sure the path in the build tool also points to the correct location where you installed it

**Comment by dylanpdx** [comment]
Not sure why but MSYS2 is not generating a home directory for your username

**Comment by Waywardson22** [comment]
Had this same issue as well. Just fixed it by doing the following:
- Uninstalling MSYS
- Reinstalling it to a new directory than the default (used C:/users/myname/msys64
