### ISSUE TITLE
Sound doesn't work "with the needed files included"

### ISSUE THREAD

**Issue by GitHubEnjoyerr** [Retro64Mod/Retro64Mod.github.io#29]
This is a "me problem" I know

**Comment by KLanausse** [comment]
Is "genfiles.exe" also in the mods folder? I also had an issue with sound until I realize the mod was trying the sounds using it

**Comment by dylanpdx** [comment]
This took me a while to track down, but it will be fixed in next version

**Comment by dylanpdx** [comment]
Fixed in latest version
