### ISSUE TITLE
Mario crashes the game after sleeping ANIMATION (NOT A FIXED DUPLICATE)

### ISSUE THREAD

**Issue by GitHubEnjoyerr** [Retro64Mod/Retro64Mod.github.io#30]
Mate, u misunderstood me there, after a bit of afk Mario goes to sleep and after that if u try to move, the game crashes
And there are 2 states of sleep animation: 1 sitting and 2 laying
(he talks about pasta in the 2nd one)

**Comment by GitHubEnjoyerr** [comment]
![Uploading 2022-03-20_20.12.56.png…]()
Example

**Comment by dylanpdx** [comment]
What version of the mod are you on? The crashing issue was fixed in version 1.18.2-1.0.3

**Comment by GitHubEnjoyerr** [comment]
Oh, thought it was the latest version but apparently, You are quick to update, I'm on 1.0.1
