### ISSUE TITLE
probleme

### ISSUE THREAD

**Issue by evalx02** [Retro64Mod/Retro64Mod.github.io#36]
hello I can't get the sm64.dll file could you help me

**Comment by evalx02** [comment]
pls

**Comment by PuppyDougan7** [comment]
you Download the build file above the mod Download and that is where you get it
PS: you will also need a US Mario 64 rom.

**Comment by evalx02** [comment]
it still doesn't work even with a rom

**Comment by evalx02** [comment]
can you send me the folder ?

**Comment by evalx02** [comment]
pls

**Comment by dylanpdx** [comment]
You have to compile the dll yourself using the build tool.

**Comment by evalx02** [comment]
but I can't get the versions so I can't compile

**Comment by dylanpdx** [comment]
Uninstall and reinstall MSYS2, old versions have issues.
No one can give you the files due to legal reasons
