### ISSUE TITLE
Punching applies insane vertical knockback to mobs

### ISSUE THREAD

**Issue by f0rttnite** [Retro64Mod/Retro64Mod.github.io#41]
Maybe it's intentional (for some reason) but Mario punches send enemies flying into the sky, enough to apply fall damage.
Would purely horizontal knockback (or at least, severely diminished vertical knockback) not be better?

**Comment by dylanpdx** [comment]
This is intentional and it's intended to replicate the Goomba knockback

https://user-images.githubusercontent.com/1337360/161442414-7d31e508-bedb-4065-b064-62ebf27fa224.mp4
