### ISSUE TITLE
Mario lacks shading

### ISSUE THREAD

**Issue by f0rttnite** [Retro64Mod/Retro64Mod.github.io#43]
Again, likely a limitation more than a bug, but Mario shows up effectively in fullbright in any situation, with his brightness only being affected by the direct light level of where he is

**Comment by dylanpdx** [comment]
Fixed in latest version

**Comment by f0rttnite** [comment]
looks a lot better than before but there's something that feels 'off' about the shading
i think it either follows the camera or it's not in the same direction as the world's shading?
i can't complain though, as i said it's a lot nicer than it was
