### ISSUE TITLE
Texture on bottom of mini-Minecraft player head flipped

### ISSUE THREAD

**Issue by kilometerbob** [Retro64Mod/Retro64Mod.github.io#57]
When in the miniature Steve mode the bottom texture for the player head is flipped

Example with my skin:
![2022-04-06_20 38 10](https://user-images.githubusercontent.com/58479577/162109293-1da0d574-f811-42dd-869c-32554bc6db83.png)
![2022-04-06_20 38 27](https://user-images.githubusercontent.com/58479577/162109324-150d8b24-23c0-4478-8744-43bd5d36d991.png)
The Purple part shown under the chin in the first image should be in the back position shown in image 2. I have checked and made sure my skin is not the issue

**Comment by dylanpdx** [comment]
This should be fixed with the new Steve model.
