### ISSUE TITLE
Sleeping in a bed as Mario will cause Minecraft to freeze up and stop responding

### ISSUE THREAD

**Issue by KLanausse** [Retro64Mod/Retro64Mod.github.io#7]
https://user-images.githubusercontent.com/66651363/158712845-8c0f473b-aba8-4bed-85ef-70963d3bdbaa.mp4

**Comment by dylanpdx** [comment]
I'll look into this. Do you by any chance not have audio working/enabled?
Might be crashing due to not being able to play the snoring sfx

**Comment by KLanausse** [comment]
Yeah. Audio wasn't playing

**Comment by KLanausse** [comment]
Yeah, audio wasn't working. I updated to the new release and it seems to be freezing a bit more randomly.

**Comment by KLanausse** [comment]
Ok, I'm 99% sure you're right about the audio thing. I let Mario idle till he did his sleep animation and the game also froze

**Comment by dylanpdx** [comment]
Fixed in 1.18.2-1.0.3
