### ISSUE TITLE
Mod Seems Incompatible With Manjaro and SteamOS

### ISSUE THREAD

**Issue by SolarNyan** [Retro64Mod/Retro64Mod.github.io#71]
I attempted to install this mod following the linux install instructions via a Manjaro desktop and the game always returns with a crash on both my desktop and Steam Deck. It will never get past the initial loading screen. Every mod loads fine until I attempt to load the SM64 ROM (which is a US version that works fine on my Windows machine).

Is this more intended to be ran through Wine rather than the native linux port? This was tested with both the PolyMC and Minecraft flatpak launchers.

**Comment by dylanpdx** [comment]
Please try installing the latest version which no longer needs compiling to work. If it's still not working, feel free to open this issue again and I'll take a look!
