### ISSUE TITLE
Antivirus

### ISSUE THREAD

**Issue by EG2603** [Retro64Mod/Retro64Mod.github.io#73]
Virus total says that the builder program is a virus
![2022-04-25](https://user-images.githubusercontent.com/104365379/165091707-3369a9e6-a60d-4979-9fb1-6a846e1c4c07.png)

**Comment by dylanpdx** [comment]
Nothing I can do about that unfortunately. You could try building from source but as of the latest version the builder is not required anymore if you follow the instructions at https://retro64mod.github.io/
