### ISSUE TITLE
Virus problem again

### ISSUE THREAD

**Issue by EG2603** [Retro64Mod/Retro64Mod.github.io#74]
Now it says the mod is a virus
![2022-04-25 (1)](https://user-images.githubusercontent.com/104365379/165116100-9652d580-c66e-4630-981d-06305468329d.png)

**Comment by dylanpdx** [comment]
Again, nothing I can really do about it as it's a false positive from the antivirus software itself, and not something I control.

If you want to be absolutely sure it's safe, review the source code in the following repositories & compile everything using the instructions in the Readme files:

https://github.com/Retro64Mod/libsm64-retro64
https://github.com/Retro64Mod/Retro64Mod
https://github.com/Retro64Mod/sm64_asset_builder (currently no build instructions for this, but installing the pyinstaller package and making a single file out of genfiles.py should work)
