### ISSUE TITLE
cant find sm64.dll

### ISSUE THREAD

**Issue by FunkyMonky420** [Retro64Mod/Retro64Mod.github.io#82]
where do i find it? 
![sm64](https://user-images.githubusercontent.com/104734956/166161446-eeab2606-fac0-47f0-a31c-650894d34d86.PNG)

**Comment by dylanpdx** [comment]
If you're using version 1.0.7 of the mod, this issue shouldn't happen. What OS are you on?

**Comment by FunkyMonky420** [comment]
> If you're using version 1.0.7 of the mod, this issue shouldn't happen. What OS are you on?

windows

**Comment by dylanpdx** [comment]
Can you send the file "latest.log" in the .minecraft/logs folder, after the problem happens?

**Comment by FunkyMonky420** [comment]
> Can you send the file "latest.log" in the .minecraft/logs folder, after the problem happens?
[latest.log](https://github.com/Retro64Mod/Retro64Mod.github.io/files/8599749/latest.log)

**Comment by dylanpdx** [comment]
Please try this version and see if you have the same issue: 
https://github.com/Retro64Mod/Retro64Mod/suites/6335604619/artifacts/228079554

**Comment by FunkyMonky420** [comment]
it worked thanks :)

**Comment by dylanpdx** [comment]
No problem! This will be part of the next version then :)
