### ISSUE TITLE
1.0.7 mod issue for mac

### ISSUE THREAD

**Issue by Thatonemariofan** [Retro64Mod/Retro64Mod.github.io#83]
With the new mod, it now crashes when minecraft loads up, rather than crashing when M is pressed.
https://pastebin.com/F7N7rua5 here is the crash log if that helps.

**Comment by Sammy3968** [comment]
How did you get the mod running without wine? If possible

**Comment by dylanpdx** [comment]
For Mac you might need to install SDL2 from brew for the mod to run. Someone on Discord had 1.0.7 working a while back with that setup

**Comment by Sammy3968** [comment]
Functional with M1?

**Comment by dylanpdx** [comment]
Yeah, Minecraft runs via Rosetta 2 for Mac users from what i've heard so it should translate the calls automatically

**Comment by ildiem** [comment]
Mac user here on 1.0.7, installing SDL2 didn't fix this issue for me so something else might be at play here, either on my end or your Discord friend's

**Comment by dylanpdx** [comment]
Can I see your crashlog? If it's an SDL2 issue you might see a line like this:
> tried: '/usr/local/opt/sdl2/lib/libSDL2-2.0.0.dylib' (no such file), '/usr/lib/libSDL2-2.0.0.dylib' (no such file)

**Comment by ildiem** [comment]
Here you go: https://gist.github.com/ildiem/cb568aaa71acf10ef146bf5bce09777e
