### ISSUE TITLE
steve skin crashes the game

### ISSUE THREAD

**Issue by XSupremoLucic** [Retro64Mod/Retro64Mod.github.io#9]
The game crashed whilst unexpected error
Error: java.lang.IllegalArgumentException: (0, 32) outside of image bounds (64, 32)
Código de error: -1

**Comment by dylanpdx** [comment]
Latest version prevents this crash but with the side effect that it will not display your player's skin.
This is due to using the old 64x32 skin format rather than the new 64x64 format. Will be fixed in the future

**Comment by XSupremoLucic** [comment]
nice
