### ISSUE TITLE
mario is gliching when he's getting closer to MC Border.

### ISSUE THREAD

**Issue by fredzio2006** [Retro64Mod/Retro64Mod.github.io#90]
movement and graphics are getting broken.
![javaw_u4ImRmamc8](https://user-images.githubusercontent.com/69014595/167166269-e9569ac8-f3a0-4df5-8b8b-4cc217170bab.png)
![javaw_VodUCwAIbc](https://user-images.githubusercontent.com/69014595/167166278-98d7dcb0-419b-45d2-b745-257e29366fbc.png)
![javaw_z1kbTHuFVs](https://user-images.githubusercontent.com/69014595/167166284-bfe030c9-ad61-4014-a231-4d9ce4adab7b.png)
![javaw_2nZlzDnGMI](https://user-images.githubusercontent.com/69014595/167166289-3ef7c28d-74af-4bc6-9f7b-200b83da6585.png)
![javaw_5ui0UVKgoT](https://user-images.githubusercontent.com/69014595/167166295-65c70ff4-4cc4-428d-b71c-e0bc14d51a4c.png)
![javaw_7bmVJ8LFcT](https://user-images.githubusercontent.com/69014595/167166304-63dd8b75-c3c9-45cf-a8e0-add9c87118ad.png)
![javaw_9f4Pt72v6z](https://user-images.githubusercontent.com/69014595/167166308-705adcbf-bdfe-4ada-81d4-db3436d1510b.png)
![javaw_aKi8fWolUW](https://user-images.githubusercontent.com/69014595/167166316-8f6da44e-0bc7-412a-bef1-5f996b39be98.png)
![javaw_BCUqx1kvbH](https://user-images.githubusercontent.com/69014595/167166321-22d06d26-0030-4997-93a5-78f798bf08a7.png)
![javaw_Jdf3YiGplS](https://user-images.githubusercontent.com/69014595/167166330-d45b90f6-a22b-4228-9523-102bfcafd273.png)
![javaw_LhGIxjNhbr](https://user-images.githubusercontent.com/69014595/167166335-f13929ab-ace0-4f3a-9b1d-e8386c39954a.png)
![javaw_qXXNV5U09G](https://user-images.githubusercontent.com/69014595/167166345-d1fb3094-d56e-487d-8874-2c6d4c787311.png)
![javaw_Rg6buY47Tp](https://user-images.githubusercontent.com/69014595/167166349-65d04d46-32e1-42fa-9ee8-122d0e8bd6ba.png)

**Comment by Lucaspec72** [comment]
looks like he's one parallel universe ahead of you xD

**Comment by dylanpdx** [comment]
Won't fix this for now, it's a limitation of the sm64 engine using floating point values for position data
