### ISSUE TITLE
Typo in install instructions ?

### ISSUE THREAD

**Issue by Lucaspec72** [Retro64Mod/Retro64Mod.github.io#91]
what should the US rom be called ?
![image](https://user-images.githubusercontent.com/48445530/167166910-d24a2bca-288d-48fc-95d9-36e27398e66f.png)

**Comment by dylanpdx** [comment]
Any name works as long as in .z64 format. It'll find it automatically

**Comment by Lucaspec72** [comment]
makes sense. counterpoint :
![image](https://user-images.githubusercontent.com/48445530/167180096-43427f61-a6cb-481d-b075-7818e2f34825.png)
the rom is the same baserom i use for the pc port, which doesn't have any problem, so idk why but it doesn't recognise the rom.

**Comment by dylanpdx** [comment]
This might be an issue with custom launchers i.e MultiMC, i'll look into it

**Comment by sonicer105** [comment]
I also have this issue. I'm using PolyMC (MultiMC Fork) on Linux

**Comment by dylanpdx** [comment]
Hi, this should be fixed in the following pre-release version, downloadable here
https://github.com/Retro64Mod/Retro64Mod/actions/runs/2355018454

**Comment by Lucaspec72** [comment]
just tried it out, and it seems that for my rom isn't the one the mod expects, so the problem is my rom. (i think it's sha1 hash is ca577bf38398d7128241424150820da5989ab35d)

**Comment by dylanpdx** [comment]
Should be fixed in 1.0.9
