### ISSUE TITLE
help

### ISSUE THREAD

**Issue by IconicPlushStars** [Retro64Mod/Retro64Mod.github.io#94]
I listened to the tutorial and it says i am missing the dll and then i went to the source code and tried to get the dll but it sill does not work. I have to play an older version of a mod. can someone help me?

**Comment by dylanpdx** [comment]
The newest version of the mod doesn't need compiling anymore, although to build an old version you'll need MSYS2 & the build tool https://github.com/Retro64Mod/retro64-GUI-build-utility

**Comment by dylanpdx** [comment]
If you still need help, please re-open the issue
