### ISSUE TITLE
Shaders messing up libsm64

### ISSUE THREAD

**Issue by TeamSoldierNub2** [Retro64Mod/Retro64Mod.github.io#99]
With shaders added (via OptiFine), it messes up how mario sees collision

Links to footage are in the clickable sentences.

*[You can't walk through doors normally](https://streamable.com/18rjpm)
*[You can't do the BLJ glitch/collision is freaking out](https://streamable.com/i893fb)

Shaders used: https://github.com/TechDevOnGitHub/Lux-Shader

**Comment by dylanpdx** [comment]
It's currently mentioned on the website (https://retro64mod.github.io/) that shaders are incompatible with the mod due to my method of generating collision data
